version: '3.8'

services:
  cam-webviewer:
    build: .
    ports:
      - "${PORT-3000}:${PORT-3000}"
    environment:
      - PORT=${PORT-3000}
      - RESET_MINUTES=${RESET_MINUTES-15}
      - CAM1=${CAM1}
      - CAM2=${CAM2}
      - CAM3=${CAM3}
      - CAM4=${CAM4}
      - CAM5=${CAM5}
      - CAM6=${CAM6}
      - CAM7=${CAM7}
    env_file:
      - .env
    restart: unless-stopped
